version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: task_manger
    environment:
      POSTGRES_USER: abdallah
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manger_db
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5234:5432"
    restart: unless-stopped

volumes:
  postgres_data: